---
title: Oslohistorier
timezone: UTC
collections:
  herfra:
    title: Herfra
    output: true
  lokka:
    title: Løkka
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: article
- scope:
    path: ''
    type: projects
  values:
    layout: project
permalink: pretty
