---
title: Oslohistorier
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  herfra:
    title: Herfra
    output: false
  lokka:
    title: Løkka
    output: false
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: app
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- package.json
