---
title: Oslohistorier
timezone: UTC
collections:
  dronningensgate:
    title: Dronningens gate
    output: false
  ferge:
    title: Ferge
    output: false
  herfra:
    title: Herfra
    output: false
  kirkeristen:
    title: Kirkeristen
    output: false
  lokka:
    title: Løkka
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: app
include:
- _redirects
exclude:
- Gemfile
- Gemfile.lock
- package.json
